### ISSUE TITLE
Deploy results in an internal server error

### ISSUE THREAD

**Issue by vostokbike** [adaptivdesign/odooku#18]
Attempted a vanilla deploy but keep getting an internal server error when trying to access the app. 
Might there be an issue with ssl?

[odoo-heroku-log.txt](https://github.com/adaptivdesign/odooku/files/983814/odoo-heroku-log.txt)

**Comment by adaptivdesign** [comment]
Looks like Odooku doesn't like running without Redis. I will fix this asap. In the mean time, try and make sure you have the free Redis tier enabled in Heroku?

It is possible to run Odooku without Redis. Redis is used as a session store. Without Redis you will have to log in every time the Heroku Dyno restarts, since session information is writting to the FS by default.

**Comment by vostokbike** [comment]
Thank you, everything is running smoothly.

**Comment by adaptivdesign** [comment]
Good to hear!

**Comment by adaptivdesign** [comment]
This issue is now completely fixed. If no REDIS_URL is present, it will fallback to the FS session.
