### ISSUE TITLE
Need to add runtime.txt to select Python 2.7

### ISSUE THREAD

**Issue by martijnthe** [adaptivdesign/odooku#19]
Thanks for your work! Trying it out now for a hobby project :)

Recently Python 3 has become the default runtime on Heroku but Odoo is not Python 3 ready.
So you'll need to add a `runtime.txt` at the root of the project with the string `python-2.7.13` in it.
https://devcenter.heroku.com/changelog-items/1169

**Comment by adaptivdesign** [comment]
Hi martijn, thats great to hear!

This should not be needed for an Odooku project, since it has it's own buildpack. The runtime.txt is something used by Heroku's Python buildpack.

If you run into any problems, let me know. Also if you are going to use this project in production (which you totally can), keep a look at at https://github.com/odooku. In a few weeks I will introduce a new iteration of this project.

**Comment by martijnthe** [comment]
Aha, gotcha.
I've not a lot of experience with Heroku.
I think I also had the Python buildpack added in the list, but it sounds like that's not required?

I'll take a look at https://github.com/odooku in a couple weeks, thanks.

**Comment by adaptivdesign** [comment]
Yes remove it, only use the Odooku buildpack
