### ISSUE TITLE
Vagrant box box-cutter/ubuntu1404-docker can not be found

### ISSUE THREAD

**Issue by rkoster** [adaptivdesign/odooku#2]
When trying to setup the development environment I encountered the following issue:

```
> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'box-cutter/ubuntu1404-docker' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'box-cutter/ubuntu1404-docker' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/box-cutter/ubuntu1404-docker"]
Error: The requested URL returned error: 404 Not Found
```

After checking [the list of available boxes by box-cutter](https://vagrantcloud.com/box-cutter) I could indeed not find a ubuntu1404 with docker.

**Comment by adaptivdesign** [comment]
I will look for a replacement box, must have had it cached on my system. Thank you!

**Comment by adaptivdesign** [comment]
I've been working on this issue, since I couldn't develop any further. I've decided to create a seperate litte project because I kept on copy pasting shell scripts. It's called "devoku", I've written some docs. Next days I'll update the Odooku docs.

Regarding the proxy mode, I'm going to get started soon on that. Currently settings up a travis test environment, before adding any new features.

**Comment by rkoster** [comment]
Nice! looking forward to trying out devoku
