### ISSUE TITLE
partically git from odoo?

### ISSUE THREAD

**Issue by grauschnabel** [adaptivdesign/odooku#5]
Hi there,

is there a way not to have to download the full odoo, but use `git clone --depth 1` instead?  pushing that to heroku seems to fail because of missing history...

Any ideas?

**Comment by adaptivdesign** [comment]
Hey,

Sorry but I'm not completely understanding your issue. Are you including Odoo yourself? Because you should not have to do that. The odooku-buildpack takes care of that. The odooku.json file specifies which exact version you want. 

See: https://github.com/adaptivdesign/odooku-buildpack/blob/9.0/lib/steps/odoo-install

I hope this helps.

**Comment by grauschnabel** [comment]
ah, ok, i understand, i have to clone this repo not odoo itself....  thanks, that should work I hope... (I'll come back if not).

**Comment by adaptivdesign** [comment]
Yes exactly. You can place your custom addons under /addons..  I will soon work on some docs.

**Comment by grauschnabel** [comment]
ok, can I use the default postgres via amazon too?

**Comment by adaptivdesign** [comment]
Yes you can. I am running this in production actually :) . Configure the DATABASE_URL to point to your aws database. If you leave out the db_name part from the DATABASE_URL, Odooku should run in multi-db mode. However I haven't tested recently tested this.

Next week I want to run my own projects in multi-db mode too. So i will give this attention. 

Also make sure you use the right version of Odooku, the default branch is 9.0, however I'm actively working on 10.0.

Finally the Odooku repository, is in essence just a template project. The main bulk of the work is done by the odooku-compat repo and odooku-buildpack repo. Since I'm missing a lot of docs, you might want to check out the odooku-compat repo, to see what it does.

**Comment by grauschnabel** [comment]
ok, this works now.  thanks for your help, but I think there are some issues in odoo 10, maybe upstream.  As example, my user can now (after working in devel mode for activating creation of partners), my user cannot read partners... :(  this whould work out of the box i think.

can we upgrade to the latest nightly odoo 10 here?

**Comment by adaptivdesign** [comment]
Yes you can, modify the odooku.json file. By default the latest Odoo 10.0 commit is downloaded every time the slug is build. As to your error, I need more detail on this. As far as I know, these kind of errors should not be caused by Odooku.

**Comment by grauschnabel** [comment]
Thanks, I thought about that, this issue is upstream or something.  I reinstalled the database after an update, so not this issue works.  But i guess there are more to come...

For the nightly i use `date > newinstall`, tracking the new install with git and push it to heroku, so I should get the new nightly. Thanks for that. And thanks for your nice work on odooku.

Martin
